# Spring props
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.session: INFO
    org.springframework.web.servlet: DEBUG
    org.hibernate: ERROR

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  servlet:
    context-path: /api

app:
  tz: GMT+9

